ANYSCALE_CLOUD_NAME="${ANYSCALE_CLOUD_NAME:-ai4s-multi-region}"

SUBSCRIPTION="${SUBSCRIPTION:-3eaeebff-de6e-4e20-9473-24de9ca067dc}"
RESOURCE_GROUP="${RESOURCE_GROUP:-aks-anyscale-rg}"
STORAGE_ACCOUNT="${STORAGE_ACCOUNT:-aksanyscalesa}"
STORAGE_CONTAINER="${STORAGE_CONTAINER:-aks-anyscale-blob}"
USER_IDENTITY_NAME="${USER_IDENTITY_NAME:-aks-anyscale-operator-mi}"

REGIONS="${REGIONS:-uksouth eastus2}"
PRIMARY_REGION="${PRIMARY_REGION:-uksouth}"

AKS_VERSION="${AKS_VERSION:-1.34.1}"
VNET_CIDR="10.192.0.0/15"
SUBNET_CIDR="10.192.0.0/19"
POD_CIDR="10.128.0.0/12"

SYSTEM_POOL_VM_SIZE="Standard_D8ds_v5"
SYSTEM_POOL_COUNT="3"
CPU_POOL_VM_SIZE="Standard_D16ds_v6"
CPU_POOL_MIN_COUNT="3"
CPU_POOL_MAX_COUNT="6"
GPU_POOL_VM_SIZE="Standard_NC24ads_A100_v4"
GPU_POOL_MIN_COUNT="0"
GPU_POOL_MAX_COUNT="3"